# Generated by Django 4.1.5 on 2023-01-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='emp_phone',
            new_name='emp_age',
        ),
    ]
