# Generated by Django 4.1.5 on 2023-01-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_phone', models.IntegerField()),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('Full Time Employee', 'FTE'), ('Trainee', 'Trainee'), ('Intern', 'Intern')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companymodel')),
            ],
        ),
    ]
