# Generated by Django 4.1.5 on 2023-01-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Backlog', '🔴'), ('InProgress', '🟡'), ('Completed', '🟢')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_drf.usermodel')),
            ],
        ),
    ]
