# Generated by Django 4.1.5 on 2023-01-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_todos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todolist_drf.todomodel'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('Backlog', '🔴 Backlog'), ('InProgress', '🟡 In Progress'), ('Completed', '🟢 Completed')], max_length=50),
        ),
    ]
