# Generated by Django 4.1.5 on 2023-01-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_drf', '0002_usermodel_user_todos_alter_todomodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_todos',
        ),
    ]
