# Generated by Django 4.2.4 on 2023-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_organization_employee_organization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
